### ISSUE TITLE
Linux -> Kernel module unload required

### ISSUE THREAD

**Issue by ramtej** [ccostes/rtl-sdr-rs#10]
Hi, 

thank you for the exciting project. 

I would just like to add that there are issues on Linux when the rtl* kernel modules are loaded. The kernel modules take over the RTL-SDR device so that the USB device can no longer be accessed.

The USB error is as follows: 

```
thread 'main' panicked at 'Unable to open SDR device!: Usb(Busy)'
```

The module can be temporarily unloaded as follows: 

```
sudo rmmod rtl2832_sdr
sudo rmmod dvb_usb_rtl28xxu
sudo rmmod rtl2832
sudo rmmod rtl8xxxu
```

Regards, 
Jiri

**Comment by ccostes** [comment]
Thanks for the report, updated the readme with your info!
