### ISSUE TITLE
rtl_sdr_blog feature error

### ISSUE THREAD

**Issue by ServiceDog** [ccostes/rtl-sdr-rs#11]
When the `rtl_sdr_blog` feature is enabled, I get the following error:

```
error[E0425]: cannot find value `enable` in this scope
   --> /home/amsmith/.cargo/git/checkouts/rtl-sdr-rs-0b6fc642719d3438/91ce6de/src/rtlsdr.rs:338:26
    |
338 |         self.set_gpio(0, enable)?;
    |                          ^^^^^^ help: a local variable with a similar name exists: `_enable`
```

Rust 1.65.0

**Comment by ccostes** [comment]
Ah thanks, looks like #9 didn't verify compilation with the feature enabled. Guess that's what I get for not having CI checks and not checking myself before merging.

Should be fixed by 4334d65f82b7bdd3d9e406f925fe9a15627b5dc3 👍
