### ISSUE TITLE
test_read_reg_u16 UT Failure

### ISSUE THREAD

**Issue by amsmith-pro** [ccostes/rtl-sdr-rs#12]
```bash
---- device::device_test::test_read_reg_u16 stdout ----
thread 'device::device_test::test_read_reg_u16' panicked at 'assertion failed: `(left == right)`
  left: `291`,
 right: `8961`', src/device/device_test.rs:67:5
 ```

Seems the issue is here:

```rust
    let data_expected = u16::to_be_bytes(0x0123);

    let mut mock_handle = MockDeviceHandle::new();
    mock_handle
        .expect_read_control()
        .times(1)
        .with(
            eq(CTRL_IN),
            eq(0),
            eq(addr),
            eq(index_expected),
            predicate::always(),
            eq(CTRL_TIMEOUT),
        )
        .returning(move |_, _, _, _, data, _| {
            data[0] = data_expected[0];  // <=============
            data[1] = data_expected[1];  // <=============
            Ok(2)
        });
```

At some place the order of the two bytes are getting flipped: 0x0123 == 291 and 0x2301 == 8961

This could be a unit test error or a fault with the `read_reg` function

Rust 1.65.0

**Comment by ccostes** [comment]
Don't have time to dig into it right now, but the fact that I was able to use this library to tune an FM station makes me think it's probably an error in the test code, though I wonder why I didn't see the test failure before.

Will look into this further when I get a chance, thanks for flagging!

**Comment by ccostes** [comment]
Turns out it was an error in the test - as the comment in `read_reg` states: `Read registers as little endian, but write as big; not sure why`, but the test code was written assuming big-endian.

Thanks for raising, fixed!
