### ISSUE TITLE
Open(index) does not appear to open the correct device

### ISSUE THREAD

**Issue by fredclausen** [ccostes/rtl-sdr-rs#14]
Following the example source, the following code appears to do the same thing:

```rust
// Open device
    let mut sdr = RtlSdr::open(0).expect("Unable to open SDR device!");
```

and

```rust
// Open device
    let mut sdr = RtlSdr::open(1).expect("Unable to open SDR device!");
```

I'm doing this on a machine with only one RTL-SDR connected. Both open the same SDR. I would expect the second code block to fail because I have only one device connected. Am I missing something, or is this an issue in the library?

**Comment by ccostes** [comment]
Good catch! I originally implemented it to simply open the first recognized device, so you're correct the `index` param is ignored.

Resolved in https://github.com/ccostes/rtl-sdr-rs/pull/18, thanks for reporting!
